#!/usr/bin/env bash

set -e

echo "===> Bundling..."
script/bootstrap --quiet

for testvar in LOGIN PASSWORD TOKEN CLIENT_ID CLIENT_SECRET
do
  staffomaticvar="STAFFOMATIC_TEST_${testvar}"
  if [[ -z "${!staffomaticvar}" ]]; then
      echo "Please export ${staffomaticvar}";
  fi
done

echo "===> Running specs..."
(unset STAFFOMATIC_LOGIN; unset STAFFOMATIC_ACCESS_TOKEN; bundle exec rake spec)
